name: Deploy Frontend (ssh → build on server)

on:
  push:
    branches: [ master ]

env:
  HOST: 65.109.86.205
  USER: p2p_user
  TARGET_DIR: /opt/p2p_front
  DEPLOY_SCRIPT: /usr/local/bin/deploy_p2p_front.sh

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ env.HOST }} >> ~/.ssh/known_hosts

    # ---------- 1. Копіюємо код ----------
    - name: Sync project to server
      run: |
        rsync -az --delete --exclude=".git" ./ \
          ${{ env.USER }}@${{ env.HOST }}:${{ env.TARGET_DIR }}/

    # ---------- 2. Реліз/рестарт контейнера ----------
    - name: Deploy (build & restart)
      run: |
        ssh ${{ env.USER }}@${{ env.HOST }} \
          "sudo ${{ env.DEPLOY_SCRIPT }}"
