name: Deploy Frontend (ssh → build on server)

on:
  push:
    branches: [ master ]

env:
  HOST: 65.109.86.205
  USER: p2p_user
  DEPLOY_SCRIPT: /usr/local/bin/deploy_p2p_front.sh

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add SSH key
      run: |
        install -m 600 -d ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ env.HOST }} >> ~/.ssh/known_hosts

    - name: Push latest code & run deploy script remotely

      run: |
        rsync -az --delete --exclude=".git" ./ ${{ env.USER }}@${{ env.HOST }}:/opt/p2p_front/
        ssh ${{ env.USER }}@${{ env.HOST }} "${{ env.DEPLOY_SCRIPT }}"

