name: Deploy Frontend to Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 65.109.86.205 >> ~/.ssh/known_hosts

    - name: Build Docker image
      run: |
        docker build -t p2p_react .

    - name: Save Docker image to archive
      run: |
        docker save p2p_react | gzip > p2p_react.tar.gz

    - name: Upload Docker image to server
      run: |
        rsync -avz p2p_react.tar.gz p2p_user@65.109.86.205:/opt/deploy/

    - name: Load Docker image and restart service
      run: |
        ssh p2p_user@65.109.86.205 << 'EOF'
          docker load < /opt/deploy/p2p_react.tar.gz
          sudo systemctl restart p2p_react.service
        EOF
